<?php
$pageTitle    = 'IP Infringement Policy';
$pageCategory = 'Legal';
$pageIcon     = 'ri-copyright-line';
$lastUpdated  = 'July 6, 2025';

$toc = '
<a href="#ownership"   class="block toc-link text-gray-600 hover:text-primary py-1 transition-colors">1. Ownership</a>
<a href="#protected"   class="block toc-link text-gray-600 hover:text-primary py-1 transition-colors">2. Protected Works</a>
<a href="#prohibited"  class="block toc-link text-gray-600 hover:text-primary py-1 transition-colors">3. Prohibited Acts</a>
<a href="#permitted"   class="block toc-link text-gray-600 hover:text-primary py-1 transition-colors">4. Permitted Use</a>
<a href="#dmca"        class="block toc-link text-gray-600 hover:text-primary py-1 transition-colors">5. Takedown Process</a>
<a href="#counter"     class="block toc-link text-gray-600 hover:text-primary py-1 transition-colors">6. Counter-Notice</a>
<a href="#repeat"      class="block toc-link text-gray-600 hover:text-primary py-1 transition-colors">7. Repeat Infringers</a>
<a href="#trademarks"  class="block toc-link text-gray-600 hover:text-primary py-1 transition-colors">8. Trademarks</a>
<a href="#thirdparty"  class="block toc-link text-gray-600 hover:text-primary py-1 transition-colors">9. Third-Party IP</a>
<a href="#contact"     class="block toc-link text-gray-600 hover:text-primary py-1 transition-colors">10. Contact</a>';

ob_start();
?>
<p>Global Apex Farmers Cooperative Nigeria Limited (<strong>"GAFCONL"</strong>) respects intellectual property rights and expects all Portal users to do the same. This policy explains what rights we own, what you may and may not do with our content, and how to report infringement.</p>

<h2 id="ownership">1. Ownership of Portal Content</h2>
<p>Unless otherwise indicated, all content on the 24/7 Registration Portal — including but not limited to software source code, database schemas, page layouts, text, graphics, logos, icons, photographs, audio clips, and downloadable materials — is the exclusive property of GAFCONL or its content suppliers and is protected under:</p>
<ul>
    <li><strong>Nigerian Copyright Act (Cap C28 LFN 2004)</strong> as amended</li>
    <li><strong>Trade Marks Act (Cap T13 LFN 2004)</strong></li>
    <li><strong>Patents and Designs Act (Cap P2 LFN 2004)</strong></li>
    <li>Applicable international treaties including the Berne Convention</li>
</ul>

<h2 id="protected">2. Protected Works</h2>
<ul>
    <li><strong>Software:</strong> The Portal's PHP application code, database structure, API integrations, and security architecture</li>
    <li><strong>Brand assets:</strong> GAFCONL name, logo, the "24/7 Registration Portal" mark, colour scheme, and taglines</li>
    <li><strong>Documents:</strong> Member registration forms, PDF templates, educational materials, and cooperative guides</li>
    <li><strong>AI outputs:</strong> Responses generated by Abinci Assistant within the Portal context</li>
    <li><strong>Database compilations:</strong> The structure and organisation of member, payment, and activity data</li>
</ul>

<h2 id="prohibited">3. Prohibited Acts</h2>
<p>Without our prior written consent you must <strong>not</strong>:</p>
<ul>
    <li>Copy, reproduce, distribute, or publicly display any Portal content</li>
    <li>Create derivative works based on our software, design, or documents</li>
    <li>Reverse-engineer, decompile, or disassemble the Portal software</li>
    <li>Remove or obscure any copyright, trademark, or proprietary notices</li>
    <li>Use our brand assets in any manner that implies endorsement or affiliation without authorisation</li>
    <li>Scrape or systematically extract data from the Portal using automated means</li>
    <li>Use content from the Portal in any external publication, website, or product without written permission</li>
</ul>

<h2 id="permitted">4. Permitted Use</h2>
<p>You may:</p>
<ul>
    <li>View and interact with Portal content for the sole purpose of using your cooperative membership services</li>
    <li>Download and print your own membership documents (ID card, dues receipts) for personal record-keeping</li>
    <li>Share the Portal's public URL to direct others to register</li>
    <li>Quote brief excerpts of our educational content for non-commercial purposes, provided you attribute GAFCONL as the source</li>
</ul>

<h2 id="dmca">5. Infringement Takedown Process</h2>
<p>If you believe content on the Portal infringes your intellectual property rights, submit a written notice to our designated IP agent containing <strong>all</strong> of the following:</p>
<ol style="list-style:decimal;padding-left:1.5rem;color:#4a5568;margin-bottom:1rem;">
    <li>Your full legal name, postal address, telephone number, and email address</li>
    <li>A description of the copyrighted work or trademark you claim has been infringed</li>
    <li>The specific URL(s) within the Portal where the allegedly infringing content is located</li>
    <li>A statement that you have a good-faith belief that the use is not authorised by the rights owner, its agent, or law</li>
    <li>A statement, made under penalty of perjury, that the information in your notice is accurate and that you are the rights owner or authorised to act on their behalf</li>
    <li>Your physical or electronic signature</li>
</ol>
<p><strong>Send to:</strong> <a href="mailto:info@globalapexfarmers.org.ng">info@globalapexfarmers.org.ng</a> with subject <strong>"IP Infringement Notice"</strong>.</p>
<p>We will acknowledge your notice within <strong>5 business days</strong> and, if valid, remove or disable access to the infringing material promptly.</p>
<p><strong>Misuse warning:</strong> submitting a knowingly false takedown notice may expose you to liability under Section 506(f) of applicable law and GAFCONL reserves the right to seek damages.</p>

<h2 id="counter">6. Counter-Notice Procedure</h2>
<p>If you believe content was removed in error, you may submit a counter-notice containing:</p>
<ul>
    <li>Your contact details</li>
    <li>Identification of the removed material and its location before removal</li>
    <li>A statement under penalty of perjury that removal was due to mistake or misidentification</li>
    <li>A statement consenting to the jurisdiction of Nigerian courts</li>
    <li>Your physical or electronic signature</li>
</ul>
<p>We will forward the counter-notice to the original complainant. If no court action is filed within 10–14 business days, we may restore the material.</p>

<h2 id="repeat">7. Repeat Infringer Policy</h2>
<p>In accordance with applicable law, GAFCONL will terminate the accounts of users who are found to be repeat infringers of intellectual property rights. A "repeat infringer" is any user who has received more than two valid takedown notices relating to their uploaded content.</p>

<h2 id="trademarks">8. Trademarks</h2>
<p>The following are registered or common-law trademarks of GAFCONL:</p>
<ul>
    <li><strong>GAFCONL</strong></li>
    <li><strong>Global Apex Farmers Cooperative Nigeria Limited</strong></li>
    <li><strong>24/7 Registration Portal</strong></li>
    <li><strong>Abinci Assistant</strong></li>
</ul>
<p>Nothing in these Terms grants you a licence to use our trademarks. Requests for trademark licences (e.g. for cooperative chapter use) must be made in writing.</p>

<h2 id="thirdparty">9. Third-Party Intellectual Property</h2>
<p>The Portal uses open-source libraries and third-party services. Their licences are acknowledged below:</p>
<ul>
    <li><strong>Tailwind CSS</strong> — MIT Licence</li>
    <li><strong>PHPMailer</strong> — LGPL 2.1</li>
    <li><strong>mPDF / TCPDF</strong> — LGPL / LGPL</li>
    <li><strong>PhpSpreadsheet</strong> — MIT</li>
    <li><strong>Three.js</strong> — MIT</li>
    <li><strong>Remix Icon</strong> — Apache 2.0</li>
    <li><strong>Inter font</strong> — SIL Open Font Licence 1.1</li>
</ul>
<p>User-uploaded content (photographs, NIN scans, signatures) remains the intellectual property of the uploading member. By uploading, you grant GAFCONL a limited licence to display and print that content solely for cooperative administration purposes.</p>

<h2 id="contact">10. Contact</h2>
<ul>
    <li><strong>IP Agent:</strong> Legal Department, GAFCONL</li>
    <li><strong>Email:</strong> <a href="mailto:info@globalapexfarmers.org.ng">info@globalapexfarmers.org.ng</a></li>
    <li><strong>Subject:</strong> "IP Infringement Notice" or "IP Licence Request"</li>
</ul>
<?php
$content = ob_get_clean();
require __DIR__ . '/layout.php';
